'use client';

import { useState } from 'react';
import { useTranslation } from 'react-i18next';

interface ProfilePictureProps {
  className?: string;
}

// A plain <picture> rather than next/image: `/_next/image` has no IMAGES
// binding on this deployment, so it is a pass-through that returns the same
// bytes with no Cache-Control after an extra Worker hop. The two WebP sources
// are generated by `scripts/process-images.mjs`; profile.jpg stays as the
// fallback for anything that cannot decode WebP.
export default function ProfilePicture({ className = '' }: ProfilePictureProps) {
  const { t } = useTranslation();
  const [failed, setFailed] = useState(false);

  return (
    <div className={`inline-block ${className}`}>
      <div className="relative h-32 w-32 overflow-hidden rounded-full bg-slate-800 ring-2 ring-primary/50 sm:h-40 sm:w-40">
        <svg
          viewBox="0 0 100 100"
          fill="currentColor"
          aria-hidden="true"
          className="absolute inset-0 h-full w-full"
        >
          <circle cx="50" cy="50" r="50" opacity="0.1" />
          <circle cx="50" cy="38" r="16" opacity="0.2" />
          <ellipse cx="50" cy="80" rx="28" ry="20" opacity="0.2" />
        </svg>
        {/* Dropping the <picture> on error leaves the placeholder visible, and
            keeps a broken-image glyph out of the ring. */}
        {!failed && (
          <picture className="relative block h-full w-full">
            <source
              type="image/webp"
              srcSet="/images/profile-256.webp 1x, /images/profile-320.webp 2x"
            />
            <img
              src="/images/profile.jpg"
              alt={t('hero.profileAlt')}
              width={160}
              height={160}
              // Above the fold in every viewport: eager, and ahead of the
              // other requests the document kicks off.
              fetchPriority="high"
              decoding="async"
              className="h-full w-full object-cover"
              onError={() => setFailed(true)}
            />
          </picture>
        )}
      </div>
    </div>
  );
}
